Fixed typo in the readme (#3)
Without this commit we would get a validation error:

ValidationError: aws.secretAccessKey is a required field

Which wouldn't make it passed the build phase